module: PallidorGenerator
author: tum-aweink
theme: fullwidth
output: ./docs
documentation: ./*.md
author_url: https://github.com/tum-aweink
github_url: https://github.com/tum-aweink/PallidorGenerator
